name: Update README timestamp
on:
  schedule: 
    - cron: "0 8 * * 1"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update timestamp
        run: |
          d=$(date -u '+%Y-%m-%d')
          sed -i "s/Last updated: .*./Last updated: $d./" README.md
      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git commit -am "chore: update README timestamp" || echo "No changes"
          git push
